
import { toast } from "@/components/ui/use-toast";

export interface Argument {
  content: string;
  side: "for" | "against";
}

export interface DebateRound {
  forArgument: string;
  againstArgument: string;
}

// Function to generate a single round of debate
export const generateDebateRound = async (
  topic: string,
  fieldName: string,
  roundNumber: number,
  previousRounds: DebateRound[] = [],
  apiKey: string = "AIzaSyBs6CqwGJJ_7FuhnhPD__RUVVTCQ_Iwd8o"
): Promise<DebateRound> => {
  try {
    console.log(`Generating round ${roundNumber} for topic: ${topic} in field: ${fieldName}`);
    
    // Construct prompt based on round number and previous rounds
    let prompt = "";
    
    if (roundNumber === 1) {
      // First round: opening arguments
      prompt = `Generate opening arguments for a debate on the topic "${topic}" from the perspective of ${fieldName}.
      
      Please provide ONE well-reasoned argument FOR the position and ONE well-reasoned argument AGAINST the position.
      
      Make both arguments substantive, persuasive, and include concrete examples or evidence.
      Keep each argument concise but substantial (about 2-3 paragraphs).
      
      Use **asterisks** around words or phrases that you want to emphasize.
      
      Format your response with clearly labeled sections for the FOR argument and AGAINST argument.`;
    } else {
      // Subsequent rounds: build on previous arguments
      prompt = `This is round ${roundNumber} of a debate on the topic "${topic}" from the perspective of ${fieldName}.

      Here are the previous rounds:
      ${previousRounds.map((round, index) => `
      ROUND ${index + 1}:
      FOR: ${round.forArgument}
      AGAINST: ${round.againstArgument}
      `).join('\n')}
      
      For round ${roundNumber}, generate ONE response FOR the position that directly addresses and rebuts the most recent AGAINST argument.
      
      Also generate ONE response AGAINST the position that directly addresses and rebuts the most recent FOR argument.
      
      Make both arguments substantive, persuasive, and include concrete examples or evidence.
      Keep each argument concise but substantial (about 2-3 paragraphs).
      
      Use **asterisks** around words or phrases that you want to emphasize.
      
      Format your response with clearly labeled sections for the FOR argument and AGAINST argument.`;
    }
    
    // Make API call to Gemini
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 2048
        }
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error("Gemini API error:", errorData);
      throw new Error(`API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error("No content generated by the API");
    }

    // Parse the generated text to extract FOR and AGAINST arguments
    const forMatch = generatedText.match(/FOR:?([\s\S]*?)(?=AGAINST:|$)/i);
    const againstMatch = generatedText.match(/AGAINST:?([\s\S]*?)(?=FOR:|$)/i);
    
    let forArgument = forMatch?.[1]?.trim() || `Could not parse FOR argument for round ${roundNumber}`;
    let againstArgument = againstMatch?.[1]?.trim() || `Could not parse AGAINST argument for round ${roundNumber}`;
    
    // Format text with asterisks to be bold and italic
    forArgument = formatEmphasis(forArgument);
    againstArgument = formatEmphasis(againstArgument);
    
    return { forArgument, againstArgument };
    
  } catch (error) {
    console.error(`Error generating round ${roundNumber}:`, error);
    throw error;
  }
};

// Helper function to format text with asterisks as bold and italic
const formatEmphasis = (text: string): string => {
  return text.replace(/\*\*(.*?)\*\*/g, '<strong><em>$1</em></strong>');
};

// Function to generate a mock debate round (for fallback)
export const generateMockDebateRound = (
  topic: string, 
  fieldName: string, 
  roundNumber: number
): DebateRound => {
  return {
    forArgument: `Mock FOR argument for round ${roundNumber} on "${topic}" from the perspective of ${fieldName}.`,
    againstArgument: `Mock AGAINST argument for round ${roundNumber} on "${topic}" from the perspective of ${fieldName}.`
  };
};

// Keep the existing mock data function (may be used for fallback)
export const generateMockDebate = (topic: string, fieldName: string): { rounds: DebateRound[] } => {
  return {
    rounds: [
      {
        forArgument: `Opening argument FOR ${topic} from the perspective of ${fieldName}.`,
        againstArgument: `Opening argument AGAINST ${topic} from the perspective of ${fieldName}.`
      },
      {
        forArgument: `Second round FOR ${topic} from the perspective of ${fieldName}, responding to the opening counter-argument.`,
        againstArgument: `Second round AGAINST ${topic} from the perspective of ${fieldName}, responding to the opening argument.`
      },
      {
        forArgument: `Third round FOR ${topic} from the perspective of ${fieldName}, defending and elaborating.`,
        againstArgument: `Third round AGAINST ${topic} from the perspective of ${fieldName}, finding flaws in the opponent's logic.`
      },
      {
        forArgument: `Fourth round FOR ${topic} from the perspective of ${fieldName}, addressing criticisms.`,
        againstArgument: `Fourth round AGAINST ${topic} from the perspective of ${fieldName}, strengthening position with examples.`
      },
      {
        forArgument: `Final round FOR ${topic} from the perspective of ${fieldName}, concluding and summarizing the strongest points.`,
        againstArgument: `Final round AGAINST ${topic} from the perspective of ${fieldName}, concluding and summarizing the strongest objections.`
      }
    ]
  };
};
