
import { toast } from "@/components/ui/use-toast";

export interface DebateRound {
  forArgument: string;
  againstArgument: string;
}

// This is a real implementation of the Gemini API client
export const generateDebateWithGemini = async (
  topic: string,
  fieldName: string,
  apiKey: string = "AIzaSyBs6CqwGJJ_7FuhnhPD__RUVVTCQ_Iwd8o"
): Promise<{ rounds: DebateRound[] }> => {
  try {
    console.log(`Generating debate for topic: ${topic} in field: ${fieldName}`);
    
    // Construct the prompt for the debate
    const prompt = `Generate a 5-round debate on the topic "${topic}" from the perspective of ${fieldName}.
    
    For each round, provide one argument FOR and one argument AGAINST.
    Round 1 should be opening arguments that present the initial position clearly and strongly.
    Rounds 2-5 should be responses to the previous round's arguments, with rebuttals and counter-points.
    
    Format each round with clear and substantive arguments. Do not include placeholders or meta-text about "this would be generated by API".
    
    Make sure the FOR arguments are persuasive with concrete examples.
    Make sure the AGAINST arguments are equally persuasive with concrete examples.
    
    Keep each argument concise but substantial (about 2-3 paragraphs).`;
    
    // Make the actual API call to Gemini
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 8192
        }
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error("Gemini API error:", errorData);
      throw new Error(`API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();
    
    // Process the response to extract the debate rounds
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error("No content generated by the API");
    }

    console.log("Generated Text:", generatedText);
    
    // Parse the generated text into debate rounds
    // This is a simplified parsing logic that expects a somewhat structured response
    const roundsData = parseDebateRounds(generatedText);
    
    return { rounds: roundsData };
    
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    toast({
      title: "Error generating debate",
      description: error instanceof Error ? error.message : "Failed to generate debate with Gemini API",
      variant: "destructive",
    });
    throw error;
  }
};

// Helper function to parse the generated text into debate rounds
function parseDebateRounds(text: string): DebateRound[] {
  // This is a simplified parser that attempts to extract FOR and AGAINST arguments
  // from the generated text. In a production environment, you might want a more robust parser
  // or instruct the AI to format the response in a specific way that's easier to parse.
  
  // First attempt: Look for structured round markers
  const rounds: DebateRound[] = [];
  
  // Try to find sections marked with Round 1, Round 2, etc.
  const roundMatches = text.match(/Round \d+[\s\S]*?(?=Round \d+|$)/g);
  
  if (roundMatches && roundMatches.length > 0) {
    for (let i = 0; i < Math.min(roundMatches.length, 5); i++) {
      const roundText = roundMatches[i];
      
      // Try to find FOR and AGAINST sections
      const forMatch = roundText.match(/FOR:?([\s\S]*?)(?=AGAINST:|$)/i);
      const againstMatch = roundText.match(/AGAINST:?([\s\S]*?)(?=FOR:|$|Round \d+)/i);
      
      const forArgument = forMatch?.[1]?.trim() || `Could not parse FOR argument for round ${i+1}`;
      const againstArgument = againstMatch?.[1]?.trim() || `Could not parse AGAINST argument for round ${i+1}`;
      
      rounds.push({ forArgument, againstArgument });
    }
  } else {
    // Fallback: Split the text into chunks and try to alternate FOR and AGAINST
    const paragraphs = text.split('\n\n').filter(p => p.trim() !== '');
    
    for (let i = 0; i < 5; i++) {
      const forIndex = i * 2;
      const againstIndex = forIndex + 1;
      
      const forArgument = forIndex < paragraphs.length 
        ? paragraphs[forIndex] 
        : `No content for FOR argument in round ${i+1}`;
        
      const againstArgument = againstIndex < paragraphs.length 
        ? paragraphs[againstIndex] 
        : `No content for AGAINST argument in round ${i+1}`;
      
      rounds.push({ forArgument, againstArgument });
    }
  }
  
  // Ensure we have exactly 5 rounds
  while (rounds.length < 5) {
    rounds.push({ 
      forArgument: `Missing content for FOR argument in round ${rounds.length + 1}`, 
      againstArgument: `Missing content for AGAINST argument in round ${rounds.length + 1}` 
    });
  }
  
  return rounds.slice(0, 5);
}

// Fallback function that returns mock data if the API fails
export const generateMockDebate = (topic: string, fieldName: string): { rounds: DebateRound[] } => {
  return {
    rounds: [
      {
        forArgument: `Opening argument FOR ${topic} from the perspective of ${fieldName}.`,
        againstArgument: `Opening argument AGAINST ${topic} from the perspective of ${fieldName}.`
      },
      {
        forArgument: `Second round FOR ${topic} from the perspective of ${fieldName}, responding to the opening counter-argument.`,
        againstArgument: `Second round AGAINST ${topic} from the perspective of ${fieldName}, responding to the opening argument.`
      },
      {
        forArgument: `Third round FOR ${topic} from the perspective of ${fieldName}, defending and elaborating.`,
        againstArgument: `Third round AGAINST ${topic} from the perspective of ${fieldName}, finding flaws in the opponent's logic.`
      },
      {
        forArgument: `Fourth round FOR ${topic} from the perspective of ${fieldName}, addressing criticisms.`,
        againstArgument: `Fourth round AGAINST ${topic} from the perspective of ${fieldName}, strengthening position with examples.`
      },
      {
        forArgument: `Final round FOR ${topic} from the perspective of ${fieldName}, concluding and summarizing the strongest points.`,
        againstArgument: `Final round AGAINST ${topic} from the perspective of ${fieldName}, concluding and summarizing the strongest objections.`
      }
    ]
  };
};
