
import { useState, useEffect } from "react";
import { DebateRound } from "@/components/DebateRound";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import { Field } from "@/components/FieldSelector";
import { useToast } from "@/components/ui/use-toast";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

interface DebateViewProps {
  topic: string;
  fields: Field[];
  onBack: () => void;
}

interface DebateData {
  rounds: {
    forArgument: string;
    againstArgument: string;
  }[];
  loading: boolean;
  error: string | null;
}

export const DebateView = ({ topic, fields, onBack }: DebateViewProps) => {
  const [activeFields] = useState(fields.filter(field => field.active));
  const [debates, setDebates] = useState<Record<string, DebateData>>({});
  const [activeTab, setActiveTab] = useState<string>(activeFields[0]?.id || "");
  const { toast } = useToast();

  // Initialize debate data structure
  useEffect(() => {
    const initialDebates: Record<string, DebateData> = {};
    activeFields.forEach(field => {
      initialDebates[field.id] = {
        rounds: Array(5).fill({ forArgument: "", againstArgument: "" }),
        loading: true,
        error: null
      };
    });
    setDebates(initialDebates);
  }, [activeFields]);

  // Generate debate for each field
  useEffect(() => {
    const generateDebate = async (field: Field, index: number) => {
      if (!field.active) return;
      
      try {
        // Add a delay for API rate limiting, staggered by field index
        if (index > 0) {
          // Show toast notification about delay
          toast({
            title: `Generating ${field.name} debate...`,
            description: "There will be a short delay due to API rate limiting.",
            duration: 5000,
          });
          
          await new Promise(resolve => setTimeout(resolve, index * 10000)); // 10 second delay per field
        }
        
        const response = await generateDebateWithGemini(topic, field.name);
        
        setDebates(prev => ({
          ...prev,
          [field.id]: {
            ...response,
            loading: false,
            error: null
          }
        }));
      } catch (error) {
        console.error(`Error generating debate for ${field.name}:`, error);
        setDebates(prev => ({
          ...prev,
          [field.id]: {
            ...prev[field.id],
            loading: false,
            error: `Failed to generate debate for ${field.name}. Please try again.`
          }
        }));
        
        toast({
          title: "Error",
          description: `Failed to generate debate for ${field.name}. Please try again.`,
          variant: "destructive",
        });
      }
    };

    // Start generating debates for each field
    activeFields.forEach((field, index) => {
      generateDebate(field, index);
    });
  }, [activeFields, topic, toast]);

  // Mock function to simulate API call
  // In a real implementation, this would call the Gemini API
  const generateDebateWithGemini = async (topic: string, fieldName: string): Promise<{ rounds: { forArgument: string; againstArgument: string }[] }> => {
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // For demonstration, return mock data
    // In a real implementation, this would call the Gemini API
    return {
      rounds: [
        {
          forArgument: `Opening argument FOR ${topic} from the perspective of ${fieldName}. This would be generated by the Gemini API in a real implementation.`,
          againstArgument: `Opening argument AGAINST ${topic} from the perspective of ${fieldName}. This would be generated by the Gemini API in a real implementation.`
        },
        {
          forArgument: `Second round FOR ${topic} from the perspective of ${fieldName}, responding to the opening counter-argument.`,
          againstArgument: `Second round AGAINST ${topic} from the perspective of ${fieldName}, responding to the opening argument.`
        },
        {
          forArgument: `Third round FOR ${topic} from the perspective of ${fieldName}, defending and elaborating.`,
          againstArgument: `Third round AGAINST ${topic} from the perspective of ${fieldName}, finding flaws in the opponent's logic.`
        },
        {
          forArgument: `Fourth round FOR ${topic} from the perspective of ${fieldName}, addressing criticisms.`,
          againstArgument: `Fourth round AGAINST ${topic} from the perspective of ${fieldName}, strengthening position with examples.`
        },
        {
          forArgument: `Final round FOR ${topic} from the perspective of ${fieldName}, concluding and summarizing the strongest points.`,
          againstArgument: `Final round AGAINST ${topic} from the perspective of ${fieldName}, concluding and summarizing the strongest objections.`
        }
      ]
    };
  };

  const renderDebateContent = (fieldId: string) => {
    const debate = debates[fieldId];
    
    if (!debate) return null;
    
    if (debate.error) {
      return (
        <div className="text-center py-10">
          <p className="text-destructive">{debate.error}</p>
          <Button variant="outline" className="mt-4">Retry</Button>
        </div>
      );
    }
    
    if (debate.loading) {
      return (
        <div className="space-y-8">
          {[1, 2, 3, 4, 5].map(round => (
            <div key={round} className="mb-8">
              <h3 className="text-xl font-semibold mb-4 border-b border-white/20 pb-2">
                Round {round}: {round === 1 ? "Opening Arguments" : "Rebuttals"}
              </h3>
              <div className="space-y-6">
                <Skeleton className="h-40 w-full" />
                <Skeleton className="h-40 w-full" />
              </div>
            </div>
          ))}
        </div>
      );
    }
    
    return (
      <div className="space-y-4">
        {debate.rounds.map((round, index) => (
          <DebateRound
            key={index}
            roundNumber={index + 1}
            forArgument={round.forArgument}
            againstArgument={round.againstArgument}
          />
        ))}
      </div>
    );
  };

  return (
    <div className="container max-w-5xl mx-auto py-8">
      <div className="flex items-center gap-4 mb-8">
        <Button variant="outline" size="icon" onClick={onBack}>
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <h1 className="text-3xl font-bold">
          Debate: <span className="text-gold">{topic}</span>
        </h1>
      </div>
      
      <Tabs 
        defaultValue={activeTab} 
        onValueChange={setActiveTab}
        className="w-full"
      >
        <TabsList className="w-full overflow-x-auto flex flex-wrap justify-start">
          {activeFields.map(field => (
            <TabsTrigger
              key={field.id}
              value={field.id}
              className="flex-shrink-0"
            >
              {field.name}
              {debates[field.id]?.loading && (
                <span className="ml-2 inline-block h-2 w-2 animate-pulse rounded-full bg-primary"></span>
              )}
            </TabsTrigger>
          ))}
        </TabsList>
        
        {activeFields.map(field => (
          <TabsContent 
            key={field.id} 
            value={field.id}
            className="mt-8 debate-card p-6 rounded-lg"
          >
            <h2 className="text-2xl font-semibold border-b border-white/20 pb-2 mb-6">
              {field.name} Perspective
            </h2>
            {renderDebateContent(field.id)}
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
};
